### ISSUE TITLE
CAS and multiple authentication handlers

### ISSUE THREAD

**Issue by iko3** [Unicon/cas-adfs-integration#13]
I connected my CAS to our corporate AD FS, is there any way to have multiple authentication handlers? For example AD FS + DatabaseAuthenticationHandler ?

Normally CAS will loop through all authentication handlers specified in the configuration until one of them succeeds, but in AD FS case user is redirected to FS's login page. Is it possible to have sort of a backdoor to get directly to another authentication handler or something?

**Comment by jtgasper3** [comment]
https://github.com/Unicon/cas-adfs-integration/blob/master/cas-server-support-wsfederation-sample-site/src/main/webapp/WEB-INF/login-webflow.xml#L88 is what triggers the redirect to ADFS. Restore that line back to the default and in the login view construct a link using the variable `WsFederationIdentityProviderUrl` (which will effective replace https://github.com/Unicon/cas-adfs-integration/blob/master/cas-server-support-wsfederation-sample-site/src/main/webapp/WEB-INF/login-webflow.xml#L202) and then the user will see the CAS login page. They can either type in credentials for use with the other handlers or click a link and be redirected to ADFS.
