### ISSUE TITLE
updating ADFS web.config

### ISSUE THREAD

**Issue by JasonEverling** [Unicon/cas-adfs-integration#9]
Are we supposed to remove anything from the standard ADFS web.config or just adding the relevant cas configurations?

When I tried to set this up, I get

Exception details: 
System.Web.HttpCompileException: c:\inetpub\adfs\ls\FormsSignIn.aspx.cs(19): error CS0029: Cannot implicitly convert type 'System.Uri' to 'string'
   at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile).....etc.....

Line 19 is as you posted,

string clearPassUri = new Uri(clearPassUrl);

Environment:

CAS 3.5.x
ADFS 2.0

Thanks,
JASON

**Comment by jtgasper3** [comment]
Hi Jason,

I'm assuming you want to CASify ADFS vs fronting CAS with ADFS, which is generally the recommended solution. The code that is listed is more like psuedo-code. (I think that is documented somewhere). It's a 90% solutions that just needs the details worked out. (I was not able copy the working directly and got together as much as I could from memory, and recorded it here.)

I'd recommend installing Visual Studio (the Visual C# for Web) and ADFS on a test server and you'll probably have the code worked out in a few minutes.

**Comment by JasonEverling** [comment]
Yes, that is what I was going to try and do. We currently have ADFS federated with Shib which in turn uses CAS logins. With this method though, the office mobile apps, do not seem to like being redirected so I had to turn off the automated ADFS IDP selection so that our users can select "sts.domain.edu" in the mobile apps and use ADFS directly. I was hoping that since this method uses the actual ADFS login form that the mobile apps would then work.

I'll setup a dev environment and see if I can get this going.

Thanks,
JASON

**Comment by jtgasper3** [comment]
@JasonEverling,

That's actually a different issue, and there is a fix. Shib needs to have a different authnContext configured for O365. Check the Shib list archive, (or open a case with us if you are an OSS subscriber). Once the change is made, everything should work again.
